const char page1[] PROGMEM =
   "<!DOCTYPE html>\n"
   "<html lang=\"en\"><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n"
   "<title>WiFi Doorbell</title>\n"
   "<style type=\"text/css\">\n"
   "div,table,input{\n"
   "border-radius: 5px;\n"
   "margin-bottom: 5px;\n"
   "box-shadow: 2px 2px 12px #000000;\n"
   "background-image: -moz-linear-gradient(top, #ffffff, #50a0ff);\n"
   "background-image: -ms-linear-gradient(top, #ffffff, #50a0ff);\n"
   "background-image: -o-linear-gradient(top, #ffffff, #50a0ff);\n"
   "background-image: -webkit-linear-gradient(top, #efffff, #50a0ff);background-image: linear-gradient(top, #ffffff, #50a0ff);\n"
   "background-clip: padding-box;\n"
   "}\n"
   "body{width:240px;display:block;margin-left:auto;margin-right:auto;text-align:center;font-family: Arial, Helvetica, sans-serif;}}\n"
   "</style>\n"
   "<script type=\"text/javascript\">\n"
   "a=document.all\n"
   "oledon=0\n"
   "pb0=0\n"
   "pb1=0\n"
   "bmot=0\n"
   "function startEvents(){\n"
   "ws = new WebSocket(\"ws://\"+window.location.host+\"/ws\")\n"
   "ws.onopen = function(evt) { }\n"
   "ws.onclose = function(evt) { alert(\"Connection closed.\"); }\n"
   "ws.onmessage = function(evt) {\n"
   " lines = evt.data.split(';')\n"
   " event=lines[0]\n"
   " data=lines[1]\n"
   " if(event == 'state')\n"
   " {\n"
   "  d=JSON.parse(data)\n"
   "  dt=new Date(d.t*1000)\n"
   "  a.time.innerHTML=dt.toLocaleTimeString()\n"
   "  for(i=0;i<16;i++){\n"
   "   dt=new Date(d.db[i]*1000)\n"
   "   document.getElementById('t'+i).innerHTML=dt.toString().split(' ')[0]+' '+dt.toLocaleTimeString()\n"
   "   document.getElementById('r'+i).setAttribute('style',d.db[i]?'':'display:none')\n"
   "  }\n"
   "  oledon=d.o\n"
   "  pb0=d.pbdb\n"
   "  pb1=d.pbm\n"
   "  dt=new Date(d.pir*1000)\n"
   "  a.mot.innerHTML=dt.toString().split(' ')[0]+' '+dt.toLocaleTimeString()\n"
   "  a.loc.value=d.loc\n"
   "  a.OLED.value=oledon?'ON ':'OFF'\n"
   "  a.MOT.value=bmot?'ON ':'OFF'\n"
   "  a.PB0.value=pb0?'ON ':'OFF'\n"
   "  a.PB1.value=pb1?'ON ':'OFF'\n"
   "  a.temp.innerHTML=d.temp+'&deg '+d.rh+'%'\n"
   "  a.wea.innerHTML=d.weather\n"
   "  a.alert.innerHTML=d.alert\n"
   "  a.wind.innerHTML='Wind '+d.wind\n"
   " }\n"
   " else if(event == 'alert')\n"
   " {\n"
   "  alert(data)\n"
   " }\n"
   "}\n"
   "}\n"
   "function setVar(varName, value)\n"
   "{\n"
   " ws.send('cmd;{\"key\":\"'+a.myKey.value+'\",\"'+varName+'\":'+value+'}')\n"
   "}\n"
   "function reset(){setVar('reset', 0)}\n"
   "function oled(){\n"
   " oledon=!oledon\n"
   " setVar('oled', oledon)\n"
   " a.OLED.value=oledon?'ON':'OFF'\n"
   "}\n"
   "function pbToggle0(){\n"
   "pb0=!pb0\n"
   "setVar('pbdb', pb0)\n"
   "a.PB0.value=pb0?'ON ':'OFF'\n"
   "}\n"
   "function pbToggle1(){\n"
   "pb1=!pb1\n"
   "setVar('pbm', pb1)\n"
   "a.PB1.value=pb1?'ON ':'OFF'\n"
   "}\n"
   "function motTog(){\n"
   "bmot=!bmot\n"
   "setVar('mot', bmot)\n"
   "a.MOT.value=bmot?'ON ':'OFF'\n"
   "}\n"
   "function setLoc(){setVar('loc', a.loc.value)}\n"
   "function sendMsg(){setVar('msg', a.msg.value)}\n"
   "</script>\n"
   "</head>\n"
   "<body onload=\"{\n"
   "key=localStorage.getItem('key')\n"
   "if(key!=null) document.getElementById('myKey').value=key\n"
   "startEvents()\n"
   "}\">\n"
   "<div><h3>WiFi Doorbell</h3>\n"
   "<table align=\"center\">\n"
   "<tr><td><div id=\"time\"></div></td><td><div id=\"temp\"></div></td></tr>\n"
   "<tr><td colspan=2>Doorbell Rings: <input type=\"button\" value=\"Clear\" id=\"resetBtn\" onClick=\"{reset()}\"></td></tr>\n"
   "<tr id=r0 style=\"display:none\"><td></td><td><div id=\"t0\"></div></td></tr>\n"
   "<tr id=r1 style=\"display:none\"><td></td><td><div id=\"t1\"></div></td></tr>\n"
   "<tr id=r2 style=\"display:none\"><td></td><td><div id=\"t2\"></div></td></tr>\n"
   "<tr id=r3 style=\"display:none\"><td></td><td><div id=\"t3\"></div></td></tr>\n"
   "<tr id=r4 style=\"display:none\"><td></td><td><div id=\"t4\"></div></td></tr>\n"
   "<tr id=r5 style=\"display:none\"><td></td><td><div id=\"t5\"></div></td></tr>\n"
   "<tr id=r6 style=\"display:none\"><td></td><td><div id=\"t6\"></div></td></tr>\n"
   "<tr id=r7 style=\"display:none\"><td></td><td><div id=\"t7\"></div></td></tr>\n"
   "<tr id=r8 style=\"display:none\"><td></td><td><div id=\"t8\"></div></td></tr>\n"
   "<tr id=r9 style=\"display:none\"><td></td><td><div id=\"t9\"></div></td></tr>\n"
   "<tr id=r10 style=\"display:none\"><td></td><td><div id=\"t10\"></div></td></tr>\n"
   "<tr id=r11 style=\"display:none\"><td></td><td><div id=\"t11\"></div></td></tr>\n"
   "<tr id=r12 style=\"display:none\"><td></td><td><div id=\"t12\"></div></td></tr>\n"
   "<tr id=r13 style=\"display:none\"><td></td><td><div id=\"t13\"></div></td></tr>\n"
   "<tr id=r14 style=\"display:none\"><td></td><td><div id=\"t14\"></div></td></tr>\n"
   "<tr id=r15 style=\"display:none\"><td></td><td><div id=\"t15\"></div></td></tr>\n"
   "<tr><td>Motion:</td><td><div id=\"mot\"></div></td></tr>\n"
   "<tr><td>Display:</td><td><input type=\"button\" value=\"OFF\" id=\"OLED\" onClick=\"{oled()}\"> Mot <input type=\"button\" value=\"OFF\" id=\"MOT\" onClick=\"{motTog()}\"></td></tr>\n"
   "<tr><td>PushBullet:</td><td><input type=\"button\" value=\"OFF\" id=\"PB0\" onClick=\"{pbToggle0()}\"> Mot <input type=\"button\" value=\"OFF\" id=\"PB1\" onClick=\"{pbToggle1()}\"></td></tr>\n"
   "<tr><td>Message:</td><td><input id='msg' type=text size=8 value=''><input value=\"Set\" type='button' onclick=\"{sendMsg()}\"></td></tr>\n"
   "<tr><td>Location:</td><td><input id='loc' type=text size=8 value=''><input value=\"Set\" type='button' onclick=\"{setLoc()}\"></td></tr>\n"
   "</table>\n"
   "<div id=\"wea\"></div>\n"
   "<div id=\"alert\"></div>\n"
   "<div id=\"wind\"></div>\n"
   "<input id=\"myKey\" name=\"key\" type=text size=50 placeholder=\"password\" style=\"width: 150px\"><input type=\"button\" value=\"Save\" onClick=\"{localStorage.setItem('key', key = document.all.myKey.value)}\">\n"
   "<br></div>\n"
   "<small>Copyright &copy 2016 CuriousTech.net</small>\n"
   "</body>\n"
   "</html>\n";
